// Source tables for the v0.2.0 metadata normalization. Kept in the repo as
// the paper trail for how the original free-text `languages` and `themes`
// tags were mapped onto the controlled vocabularies in data/vocab/.
// See docs/NORMALIZATION-v0.2.md for the human-readable version.

// [canonical name, ISO 639-3 or null, type, alt names]
// type: "language" | "macrolanguage" | "sign language" | "collective"
// ISO 639-3 codes are only given where the mapping is unambiguous; a code
// on a macrolanguage names the macrolanguage, not a specific variety.
export const LANGUAGES = [
  ["Acholi", "ach", "language", []],
  ["Afrikaans", "afr", "language", []],
  ["Ainu", "ain", "language", []],
  ["American Sign Language", "ase", "sign language", ["ASL"]],
  ["Amharic", "amh", "language", []],
  ["Arabic", "ara", "macrolanguage", []],
  ["Armenian", "hye", "language", []],
  ["Aymara", "aym", "macrolanguage", []],
  ["Bambara", "bam", "language", ["Bamanankan"]],
  ["Basque", "eus", "language", ["Euskara"]],
  ["Bengali", "ben", "language", ["Bangla"]],
  ["Bislama", "bis", "language", []],
  ["Bosnian", "bos", "language", []],
  ["Bulgarian", "bul", "language", []],
  ["Cantonese", "yue", "language", ["Yue Chinese"]],
  ["Chinese", "zho", "macrolanguage", []],
  ["Cook Islands Māori", "rar", "language", ["Rarotongan", "Cook Islands Maori"]],
  ["Croatian", "hrv", "language", []],
  ["Czech", "ces", "language", []],
  ["Danish", "dan", "language", []],
  ["Dari", "prs", "language", []],
  ["Dutch", "nld", "language", []],
  ["English", "eng", "language", []],
  ["Estonian", "est", "macrolanguage", []],
  ["Ewe", "ewe", "language", []],
  ["Fijian", "fij", "language", ["iTaukei"]],
  ["Finnish", "fin", "language", []],
  ["French", "fra", "language", []],
  ["Fulfulde", "ful", "macrolanguage", ["Fula", "Fulani", "Pulaar"]],
  ["Ga", "gaa", "language", []],
  ["Ge'ez", "gez", "language", ["Geez", "Classical Ethiopic"]],
  ["Georgian", "kat", "language", []],
  ["German", "deu", "language", []],
  ["Greek", "ell", "language", []],
  ["Gujarati", "guj", "language", []],
  ["Haitian Creole", "hat", "language", ["Kreyòl ayisyen"]],
  ["Hassaniya Arabic", "mey", "language", ["Hassaniya"]],
  ["Hausa", "hau", "language", []],
  ["Hebrew", "heb", "language", []],
  ["Hindi", "hin", "language", []],
  ["Hmong", "hmn", "macrolanguage", []],
  ["Hungarian", "hun", "language", []],
  ["Icelandic", "isl", "language", []],
  ["Ilocano", "ilo", "language", ["Ilokano"]],
  ["Indonesian", "ind", "language", ["Bahasa Indonesia"]],
  ["Innu-aimun", "moe", "language", ["Innu", "Montagnais"]],
  ["Inuktitut", "iku", "macrolanguage", []],
  ["Irish", "gle", "language", ["Irish Gaelic"]],
  ["Italian", "ita", "language", []],
  ["Jamaican Patois", "jam", "language", ["Jamaican Creole"]],
  ["Japanese", "jpn", "language", []],
  ["Karay-a", "krj", "language", ["Kinaray-a"]],
  ["Karelian", "krl", "language", []],
  ["Kazakh", "kaz", "language", []],
  ["Khmer", "khm", "language", []],
  ["Kikongo", "kon", "macrolanguage", ["Kongo"]],
  ["Kinyarwanda", "kin", "language", []],
  ["Korean", "kor", "language", []],
  ["Kurdish", "kur", "macrolanguage", ["Kurmanji", "Sorani"]],
  ["Kyrgyz", "kir", "language", ["Kirghiz"]],
  ["Latvian", "lav", "macrolanguage", []],
  ["Lingala", "lin", "language", []],
  ["Lithuanian", "lit", "language", []],
  ["Luo", "luo", "language", ["Dholuo"]],
  ["Malagasy", "mlg", "macrolanguage", []],
  ["Malay", "msa", "macrolanguage", []],
  ["Mandarin Chinese", "cmn", "language", ["Mandarin"]],
  ["Maninka", null, "language", ["Malinke"]],
  ["Māori", "mri", "language", ["Maori", "te reo Māori"]],
  ["Marshallese", "mah", "language", []],
  ["Nepali", "nep", "macrolanguage", []],
  ["Ndebele", "nde", "language", ["North Ndebele", "isiNdebele"]],
  ["Northern Sámi", "sme", "language", ["Northern Sami"]],
  ["Norwegian", "nor", "macrolanguage", []],
  ["Okinawan", "ryu", "language", ["Central Okinawan", "Uchinaaguchi"]],
  ["Oromo", "orm", "macrolanguage", ["Afaan Oromoo"]],
  ["Pashto", "pus", "macrolanguage", []],
  ["Persian", "fas", "macrolanguage", ["Farsi"]],
  ["Polish", "pol", "language", []],
  ["Portuguese", "por", "language", []],
  ["Punjabi", "pan", "language", ["Panjabi"]],
  ["Quechua", "que", "macrolanguage", []],
  ["Romani", "rom", "macrolanguage", []],
  ["Romanian", "ron", "language", []],
  ["Romansh", "roh", "language", []],
  ["Russian", "rus", "language", []],
  ["Scots", "sco", "language", []],
  ["Scottish Gaelic", "gla", "language", ["Gàidhlig"]],
  ["Serbian", "srp", "language", []],
  ["Seto", null, "language", []],
  ["Setswana", "tsn", "language", ["Tswana"]],
  ["Shona", "sna", "language", []],
  ["Sindhi", "snd", "language", []],
  ["Sinhala", "sin", "language", ["Sinhalese"]],
  ["Slovak", "slk", "language", []],
  ["Slovenian", "slv", "language", ["Slovene"]],
  ["Spanish", "spa", "language", ["Castilian"]],
  ["Swahili", "swa", "macrolanguage", ["Kiswahili"]],
  ["Swazi", "ssw", "language", ["siSwati", "Swati"]],
  ["Swedish", "swe", "language", []],
  ["Tagalog", "tgl", "language", []],
  ["Taiwanese Hokkien", "nan", "language", ["Taiwanese", "Min Nan"]],
  ["Tajik", "tgk", "language", []],
  ["Tamasheq", "tmh", "macrolanguage", ["Tamashek", "Tuareg"]],
  ["Tamazight", null, "language", ["Berber", "Amazigh"]],
  ["Tamil", "tam", "language", []],
  ["Tetum", "tet", "language", ["Tetun"]],
  ["Thai", "tha", "language", []],
  ["Tshiluba", "lua", "language", ["Luba-Kasai", "Luba-Lulua"]],
  ["Turkish", "tur", "language", []],
  ["Twi", "twi", "language", []],
  ["Ukrainian", "ukr", "language", []],
  ["Umbundu", "umb", "language", []],
  ["Urdu", "urd", "language", []],
  ["Uzbek", "uzb", "macrolanguage", []],
  ["Vietnamese", "vie", "language", []],
  ["Võro", "vro", "language", ["Voro"]],
  ["Welsh", "cym", "language", ["Cymraeg"]],
  ["Wolof", "wol", "language", []],
  ["Xhosa", "xho", "language", ["isiXhosa"]],
  ["Yiddish", "yid", "macrolanguage", []],
  ["Yoruba", "yor", "language", []],
  ["Zarma", "dje", "language", ["Djerma", "Zarmaciine"]],
  ["Zulu", "zul", "language", ["isiZulu"]],
  // Collective categories: used only where the source names a group of
  // languages rather than individual ones. The original wording is kept
  // per record in `language_note`.
  ["Aboriginal and Torres Strait Islander languages", null, "collective", []],
  ["Indigenous languages of the Americas", null, "collective", []],
  ["Mayan languages", null, "collective", []],
  ["Sámi languages", null, "collective", ["Sami", "Saami"]],
  ["Multiple languages", null, "collective", []],
];

// Old free-text tag -> canonical name. Tags not listed map to themselves.
// A tag mapping to a collective term also has its original wording copied
// into the record's `language_note`, so no information is lost.
export const LANGUAGE_RENAMES = {
  "Mandarin": "Mandarin Chinese",
  "Maori": "Māori",
  "Voro": "Võro",
  "Basque (Euskara)": "Basque",
  "iTaukei (Fijian)": "Fijian",
  "Kurdish (Kurmanji, Sorani)": "Kurdish",
  "Northern Sami": "Northern Sámi",
  "Sami": "Sámi languages",
  "Cook Islands Maori": "Cook Islands Māori",
  "Indigenous languages": "Indigenous languages of the Americas",
  "Indigenous languages of Mexico": "Indigenous languages of the Americas",
  "multiple Indigenous languages": "Indigenous languages of the Americas",
  "multiple Indigenous languages of the Americas": "Indigenous languages of the Americas",
  "multiple Indigenous Latin American languages": "Indigenous languages of the Americas",
  "multiple Alaska Native languages": "Indigenous languages of the Americas",
};
// Every remaining tag matching this pattern maps to "Multiple languages".
export const COLLECTIVE_PATTERN = /^(multiple|various)\b/i;
// Renames whose original wording should be preserved in language_note.
export const NOTE_WORTHY = (oldTag, newTag) =>
  COLLECTIVE_PATTERN.test(oldTag) ||
  oldTag === "Kurdish (Kurmanji, Sorani)" ||
  (newTag !== oldTag && LANGUAGES.find((l) => l[0] === newTag)?.[2] === "collective");

// Thematic taxonomy: [canonical term, group, scope note]
export const THEME_GROUPS = [
  ["oral-tradition", "Oral tradition & folklore"],
  ["music", "Music, performance & broadcasting"],
  ["language", "Language & linguistics"],
  ["war", "War & conflict"],
  ["mass-violence", "Genocide & mass violence"],
  ["rights", "Human rights & justice"],
  ["migration", "Migration & displacement"],
  ["colonialism", "Colonialism & Indigenous histories"],
  ["memory", "Memory & community"],
  ["history", "History & politics"],
  ["labor", "Labor"],
  ["gender", "Gender & sexuality"],
  ["disability", "Disability & Deaf histories"],
  ["religion", "Religion & belief"],
  ["science", "Science, environment & disaster"],
];

export const THEMES = [
  ["oral tradition", "oral-tradition", "Transmitted verbal art, narrative, and knowledge: epics, genealogies, proverbs, tales."],
  ["folklore", "oral-tradition", "Folk narrative, belief, and custom as documented by folklorists."],
  ["folklife", "oral-tradition", "Everyday traditional culture — crafts, foodways, occupations — as a documentation field."],
  ["epic performance", "oral-tradition", "Recorded performances of long-form oral epics."],
  ["griot heritage", "oral-tradition", "West African jeli/griot hereditary oral-historian traditions."],
  ["divination", "oral-tradition", "Divinatory corpora and their oral transmission (e.g. Ifá)."],
  ["masquerade", "oral-tradition", "Masquerade performance traditions and their oral/sung components."],
  ["manuscripts", "oral-tradition", "Collections where manuscript holdings sit alongside oral materials."],
  ["music", "music", "Recorded music, song, and musical performance."],
  ["ethnomusicology", "music", "Field recordings made within ethnomusicological research."],
  ["broadcast history", "music", "Radio/TV archives and the history of broadcasting."],
  ["language documentation", "language", "Recordings made to document a language, often endangered."],
  ["linguistics", "language", "Collections created for or used in linguistic research."],
  ["war and conflict", "war", "Experiences of war and armed conflict, combatant and civilian."],
  ["military history", "war", "Military service and institutions."],
  ["resistance history", "war", "Resistance movements, partisan and underground activity."],
  ["nuclear history", "war", "Nuclear weapons, testing, and atomic-bombing survivors."],
  ["peace", "war", "Peace-building and peace movements."],
  ["genocide", "mass-violence", "Genocide and its survivors, perpetrators, and witnesses."],
  ["Holocaust", "mass-violence", "The Holocaust/Shoah."],
  ["state terrorism", "mass-violence", "State violence against civilian populations."],
  ["totalitarianism", "mass-violence", "Life under totalitarian and authoritarian regimes."],
  ["human rights", "rights", "Human-rights violations and advocacy."],
  ["civil rights", "rights", "Civil-rights movements and struggles for legal equality."],
  ["transitional justice", "rights", "Truth commissions, trials, and post-conflict justice processes."],
  ["memory and reconciliation", "rights", "Post-conflict memory work and reconciliation."],
  ["incarceration", "rights", "Imprisonment, internment, and detention."],
  ["apartheid", "rights", "Apartheid in South Africa and its legacy."],
  ["migration", "migration", "Voluntary and economic migration, immigration, diaspora."],
  ["displacement", "migration", "Forced displacement of people from their homes or lands."],
  ["refugees", "migration", "Refugee experience and asylum."],
  ["forced removal", "migration", "State-directed removals and relocations."],
  ["Partition", "migration", "The 1947 Partition of British India."],
  ["Nakba", "migration", "The 1948 Palestinian displacement."],
  ["colonial history", "colonialism", "Colonial rule and its aftermath."],
  ["indigenous history", "colonialism", "Histories told by and about Indigenous peoples."],
  ["residential schools", "colonialism", "Residential/boarding school systems for Indigenous children."],
  ["community memory", "memory", "Local and community-level remembrance."],
  ["national memory", "memory", "Nationally framed memory projects."],
  ["memory", "memory", "Memory studies framing not captured by a narrower term."],
  ["everyday life", "memory", "Ordinary lives and daily experience."],
  ["family history", "memory", "Family and intergenerational history."],
  ["urban history", "memory", "Cities, neighborhoods, and urban change."],
  ["history", "history", "General historical documentation with no narrower theme recorded."],
  ["social history", "history", "Social structures and experience of ordinary people."],
  ["political history", "history", "Political life, movements, and institutions."],
  ["labor history", "labor", "Work, workers, and labor movements."],
  ["women's history", "gender", "Women's lives and experiences."],
  ["LGBTQ+ history", "gender", "LGBTQ+ lives, communities, and activism."],
  ["Deaf history", "disability", "Deaf communities and signed-language history."],
  ["disability rights", "disability", "Disability experience and rights movements."],
  ["religion", "religion", "Religious life, practice, and institutions."],
  ["science", "science", "Science and scientists."],
  ["disaster and survivor testimony", "science", "Natural and industrial disasters and survivors' accounts."],
];

export const THEME_RENAMES = {
  "politics": "political history",
  "labor": "labor history",
  "armed conflict": "war and conflict",
};
